<!-- Introduction -->
<script setup lang="ts">
import { Heading, Para, En, Zh } from '../../../components/paper'
</script>

<template>
<Heading :level="1" en="Introduction" zh="引言" />

<Para>
  <En>Recent work on compute-optimal language models~\cite{hoffmann2022training} shows that many previously trained large language models (LLMs, which we define as having more than one billion parameters) could have attained better performance for a given compute budget by training a smaller model on more data. Notably, the 70-billion parameter Chinchilla model~\cite{hoffmann2022training} outperforms the 280-billion parameter Gopher model~\cite{rae2021scaling} while using a similar compute budget by being trained on four times more data. Extrapolating these laws for compute allocation (hereafter "Chinchilla scaling laws") to a 530 billion parameter model, such as the under-trained MT-NLG model~\cite{smith2022using}, would require training on a massive 11 trillion tokens, corresponding to more than 30 terabytes of text data. For most languages, available data is several orders of magnitude smaller, meaning that LLMs in those languages are already data-constrained. \citet{villalobos2022will} estimate that even high-quality English language data will be exhausted by the year 2024 given the Chinchilla scaling laws and the trend of training ever-larger models. This motivates the question~\citep{villalobos2022will,nostalgebraist}: what should we do when we run out of data?</En>
  <Zh>最近关于计算最优语言模型的工作~\cite{hoffmann2022training}表明：对于给定的计算预算，许多此前训练的大语言模型（LLM，本文定义为参数量超过 10 亿的模型）本可以通过“用更多数据训练更小的模型”来获得更好的性能。值得注意的是，700 亿参数的 Chinchilla 模型~\cite{hoffmann2022training}在相近的计算预算下，凭借四倍于后者的训练数据，性能超过了 2800 亿参数的 Gopher 模型~\cite{rae2021scaling}。若把这类计算分配定律（下称“Chinchilla 缩放定律”）外推到 5300 亿参数的模型（如训练不足的 MT-NLG~\cite{smith2022using}），将需要在高达 11 万亿词元的庞大数据上训练，相当于超过 30TB 的文本数据。对大多数语言而言，可用数据的规模要小若干个数量级，这意味着这些语言的 LLM 已经处于数据受限状态。\citet{villalobos2022will} 估计，按照 Chinchilla 缩放定律与不断训练更大模型的趋势，即便是高质量的英文数据也将在 2024 年前耗尽。这引出了一个问题~\citep{villalobos2022will,nostalgebraist}：当数据耗尽时，我们该怎么办？</Zh>
</Para>

<Para>
  <En>In this work we investigate scaling large language models in a data-constrained regime, and whether training an LLM with multiple epochs of repeated data impacts scaling. Using multiple epochs is, of course, standard in machine learning generally; however, most prior large language models have been trained for a single epoch~\citep{komatsuzaki2019one,brown2020language} and some work explicitly advocates against reusing data~\citep{hernandez2022scaling}. An exception is the recent Galactica models~\cite{taylor2022galactica} that were trained for 4.25 epochs and exhibit continually decreasing validation loss and improving downstream performance throughout training. However, the experiments of Galactica do not compare this setup to an alternative non-data-constrained model trained for one epoch on unique data. Without this comparison, it is difficult to quantify the trade-off between additional compute versus additional data collection.</En>
  <Zh>本文研究数据受限情形下大语言模型的扩展问题，以及用多个 epoch 的重复数据训练 LLM 是否会影响扩展行为。当然，多个 epoch 在整个机器学习领域是常规做法；但以往的大语言模型大多只训练单个 epoch~\citep{komatsuzaki2019one,brown2020language}，且一些工作明确反对复用数据~\citep{hernandez2022scaling}。一个例外是近期的 Galactica 模型~\cite{taylor2022galactica}，它们训练了 4.25 个 epoch，并在整个训练过程中验证损失持续下降、下游性能不断提升。然而，Galactica 的实验并未将该设置与在等量全新数据上训练单个 epoch 的非数据受限模型进行对照。缺少这一对照，就难以量化“额外计算”与“额外收集数据”之间的权衡。</Zh>
</Para>

<Para>
  <En>Our main focus is to quantify the impact of multiple epochs in LLM training such that practitioners can decide how to allocate compute when scaling models. Toward this end, we assembled a battery of empirical training runs of varying data and compute constraints. Specifically, we train more than 400 models ranging from 10 million to 9 billion parameters for up to 1500 epochs and record final test loss. We use these results to fit a new \emph{data-constrained scaling law} that generalizes the Chinchilla scaling law~\citep{hoffmann2022training} to the repeated data regime and yields a better prediction of loss in this setting. \autoref{fig:returnalloc} summarizes our main results targeting the value of repeated data (\textit{Return}) and optimal allocation of resources in that regime (\textit{Allocation}). We find that, while models trained for a single epoch consistently have the best validation loss per compute, differences tend to be \emph{insignificant} among models trained for up to 4 epochs and do not lead to differences in downstream task performance. Additional epochs continue to be beneficial, but returns eventually diminish to zero. We find that, in the data-constrained regime, allocating new compute to both more parameters and epochs is necessary, and that epochs should be scaled slightly faster. These findings suggest a simple way to continue scaling total training compute budgets further ahead in the future than the previously anticipated limits.</En>
  <Zh>我们的核心目标是量化多个 epoch 对 LLM 训练的影响，使从业者在扩展模型时能够据此决定计算资源的分配方式。为此，我们组织了一系列在不同数据与计算约束下的实证训练运行：具体训练了 400 多个模型，参数量从 1000 万到 90 亿不等，最多训练 1500 个 epoch，并记录最终测试损失。我们用这些结果拟合出一条新的\emph{数据受限缩放定律}，它将 Chinchilla 缩放定律~\citep{hoffmann2022training}推广到重复数据的情形，并在该设定下给出更准确的损失预测。\autoref{fig:returnalloc} 总结了我们的主要结果，即重复数据的价值（\textit{Return}，回报）以及该情形下资源的最佳分配方式（\textit{Allocation}，分配）。我们发现：虽然单 epoch 训练的模型在单位计算量上始终具有最佳的验证损失，但训练至多 4 个 epoch 的各模型之间的差异往往\emph{微不足道}，也不会导致下游任务性能的差异。更多 epoch 仍有益处，但回报最终递减至零。我们发现，在数据受限情形下，有必要把新增计算同时分配给更多参数与更多 epoch，且 epoch 的扩展应略快于参数。这些发现提示了一条简单的路径，使总训练计算预算在未来能够超越此前预期的极限继续扩展。</Zh>
</Para>

<Para>
  <En>Finally, given the challenges imposed by data constraints, we consider methods complementary to repeating for improving downstream accuracy without adding new natural language data. Experiments consider incorporating code tokens and relaxing data filtering. For code, English LLMs, such as PaLM~\cite{chowdhery2022palm} or Gopher~\cite{rae2021scaling}, are trained on a small amount of code data alongside natural language data, though no benchmarking was reported to justify that decision. We investigate training LLMs on a mix of language data and Python data at 10 different mixing rates and find that mixing in code is able to provide a 2$\times$ increase in effective tokens even when evaluating only natural language tasks. For filtering, we revisit perplexity and deduplication filtering strategies on both noisy and clean datasets and find that data filtering is primarily effective for noisy datasets.</En>
  <Zh>最后，面对数据约束带来的挑战，我们考虑了与重复互补的方法，在不新增自然语言数据的前提下提升下游准确率。实验考察了两种手段：加入代码词元，以及放宽数据过滤。就代码而言，PaLM~\cite{chowdhery2022palm}、Gopher~\cite{rae2021scaling} 等英文 LLM 在自然语言数据之外还使用了少量代码数据训练，但当时并未报告基准测试来支持这一决定。我们研究了在语言数据与 Python 数据的混合数据上训练 LLM，共采用 10 种不同的混合比例，发现即使只在自然语言任务上评估，混入代码也能带来 2$\times$ 的有效词元提升。在数据过滤方面，我们在含噪与干净两类数据集上重新审视了困惑度过滤与去重过滤策略，发现数据过滤主要对含噪数据集有效。</Zh>
</Para>
</template>
