<!-- Related Work -->
<script setup lang="ts">
import { Heading, Para, En, Zh } from '../../../components/paper'
</script>

<template>
<Heading :level="1" en="Related Work" zh="相关工作" />

<Para>
  <En>\textbf{Large language models} Scaling up transformer language models~\cite{vaswani2017attention} across parameter count and training data has been shown to result in continuous performance gains~\cite{chowdhery2022palm}. Starting with the 1.4 billion parameter GPT-2 model~\cite{radford2019language}, a variety of scaled-up language models have been trained, commonly referred to as large language models (LLMs). They can be grouped into dense models~\cite{brown2020language,Khrushchev_YaLM_100B_2022,lieber2021jurassic,rae2021scaling,chung2022scaling,black2022gpt,zhang2022opt,thoppilan2022lamda,su2022welm,taylor2022galactica,zeng2022glm,scao2022bloom,li2023starcoder,luukkonen2023fingpt} and sparse models~\cite{fedus2021switch,zeng2021pangu,du2022glam,zoph2022designing} depending on whether each forward pass makes use of all parameters. These models are generally pre-trained to predict the next token in a sequence, which makes them applicable to various language tasks directly after pre-training~\cite{brown2020language,wei2022chain,kojima2022large,muennighoff2022sgpt,srivastava2022beyond} by reformulating said NLP tasks as context continuation tasks (see~\cite{DBLP:journals/corr/abs-1806-08730} for an earlier proposal on this topic). We focus on the most common scenario, where a dense transformer model is trained to do next-token prediction on a large corpus and evaluated directly after pre-training using held-out loss or zero- to few-shot prompting.</En>
  <Zh>\textbf{大语言模型} 在参数量与训练数据两个维度上扩展 transformer 语言模型~\cite{vaswani2017attention}已被证明能带来持续的性能提升~\cite{chowdhery2022palm}。从 14 亿参数的 GPT-2 模型~\cite{radford2019language}开始，人们训练了多种扩大规模的语言模型，通常称为大语言模型（LLM）。依据每次前向传播是否使用全部参数，它们可分为稠密模型~\cite{brown2020language,Khrushchev_YaLM_100B_2022,lieber2021jurassic,rae2021scaling,chung2022scaling,black2022gpt,zhang2022opt,thoppilan2022lamda,su2022welm,taylor2022galactica,zeng2022glm,scao2022bloom,li2023starcoder,luukkonen2023fingpt}与稀疏模型~\cite{fedus2021switch,zeng2021pangu,du2022glam,zoph2022designing}。这些模型通常以预测序列中的下一个词元为目标进行预训练，从而只需把相应 NLP 任务重新表述为上下文续写任务，即可在预训练完成后直接应用于各种语言任务~\cite{brown2020language,wei2022chain,kojima2022large,muennighoff2022sgpt,srivastava2022beyond}（这一思路更早的提议见~\cite{DBLP:journals/corr/abs-1806-08730}）。我们关注最常见的场景：在大型语料库上训练稠密 transformer 模型做下一词元预测，并在预训练后直接用留出损失或零样本到少样本提示进行评估。</Zh>
</Para>

<Para>
  <En>\textbf{Scaling laws} Prior work has estimated an optimal allocation of compute for the training of LLMs. \citet{kaplan2020scaling} suggested a 10$\times$ increase in compute should be allocated to a 5.5$\times$ increase in model size and a 1.8$\times$ increase in training tokens. This first scaling law has led to the creation of very large models trained on relatively little data, such as the 530 billion parameter MT-NLG model trained on 270 billion tokens~\cite{smith2022using}. More recent work~\cite{hoffmann2022training}, however, showed that model size and training data should rather be scaled in equal proportions. These findings called for a renewed focus on the scaling of pre-training data rather than scaling model size via complex parallelization strategies~\cite{shoeybi2019megatron,rasley2020deepspeed,bian2021colossal,narayanan2021efficient}. Up-sampling is often employed when pre-training data is partly limited, such as data from a high-quality domain like Wikipedia or text in a rare language for training multilingual LLMs~\cite{lin2021few,orlanski2023measuring}. \citet{hernandez2022scaling} study up-sampling of data subsets and find that repeating only 0.1\% of training data 100 times significantly degrades performance. In contrast, our work focuses on repeating the entire pre-training corpus for multiple epochs rather than up-sampling parts of it.</En>
  <Zh>\textbf{缩放定律} 已有工作对 LLM 训练的最优计算分配进行了估计。\citet{kaplan2020scaling} 提出，计算量增加 10$\times$ 时应分配给模型规模增加 5.5$\times$、训练词元数增加 1.8$\times$。这第一条缩放定律催生了一批在相对较少数据上训练的超大模型，例如在 2700 亿词元上训练的 5300 亿参数 MT-NLG 模型~\cite{smith2022using}。然而更近的工作~\cite{hoffmann2022training}表明，模型规模与训练数据应按相同比例扩展。这些发现促使人们重新关注预训练数据的扩展，而非借助复杂的并行策略来扩展模型规模~\cite{shoeybi2019megatron,rasley2020deepspeed,bian2021colossal,narayanan2021efficient}。当预训练数据部分受限时（例如维基百科这类高质量领域的数据，或训练多语言 LLM 时的稀有语言文本），人们常采用上采样（up-sampling）~\cite{lin2021few,orlanski2023measuring}。\citet{hernandez2022scaling} 研究了数据子集的上采样，发现仅把 0.1\% 的训练数据重复 100 次就会显著降低性能。与之相反，我们的工作关注把整个预训练语料库重复多个 epoch，而非对其中一部分上采样。</Zh>
</Para>

<Para>
  <En>\textbf{Alternative data strategies} Large pre-training datasets are commonly filtered to remove undesired samples or reduce noise~\cite{sorscher2022beyond}. Perplexity-based filtering, whereby a trained model is used to filter out samples with high perplexity, has been found beneficial to reduce noise in web-crawled datasets~\cite{wenzek2019ccnet}. Mixing of data is employed for the pre-training data of multilingual LLMs, where text data from different languages is combined~\cite{conneau2019unsupervised,xue2020mt5,soltan2022alexatm,muennighoff2022crosslingual}. However, both for code and natural language models, mixing different (programming) languages has been reported to under-perform monolingual models~\cite{nijkamp2022codegen,virtanen2019multilingual}. Some work has investigated mixing code and natural language data for prediction tasks, such as summarizing code snippets~\cite{iyer2016summarizing} or predicting function names~\cite{allamanis2015suggesting}. Several pre-training datasets for LLMs include low amounts of code data~\cite{gao2020pile,rae2021scaling,scao2022bloom}. However, these past works generally do not provide any ablation on the drawbacks of including code or the benefits for natural language task performance. We perform a detailed benchmarking of mixing Python and natural language in LLM pre-training at 10 different mixing rates.</En>
  <Zh>\textbf{替代性数据策略} 大型预训练数据集通常会经过过滤以去除不想要的样本或降低噪声~\cite{sorscher2022beyond}。基于困惑度的过滤——即用一个训练好的模型过滤掉困惑度高的样本——已被证明有利于降低网页爬取数据集中的噪声~\cite{wenzek2019ccnet}。多语言 LLM 的预训练数据常采用数据混合，即把来自不同语言的文本数据合并在一起~\cite{conneau2019unsupervised,xue2020mt5,soltan2022alexatm,muennighoff2022crosslingual}。然而，无论是代码模型还是自然语言模型，都有报告称混合不同（编程）语言的数据会逊于单语模型~\cite{nijkamp2022codegen,virtanen2019multilingual}。一些工作研究过在预测任务中混合代码与自然语言数据，例如摘要代码片段~\cite{iyer2016summarizing}或预测函数名~\cite{allamanis2015suggesting}。若干 LLM 预训练数据集包含少量代码数据~\cite{gao2020pile,rae2021scaling,scao2022bloom}，但这些已有工作一般没有对加入代码的弊端或其对自然语言任务性能的益处做任何消融实验。我们在 10 种不同混合比例下，对 LLM 预训练中 Python 与自然语言数据的混合进行了细致的基准评测。</Zh>
</Para>
</template>
