<!-- Do Excess Parameters Hurt, Plateau or Help? -->
<script setup lang="ts">
import { Heading, Para, En, Zh, Figure, Equation } from '../../../components/paper'
</script>

<template>
<Heading :level="1" label="sec:losscomp" appendix en="Do Excess Parameters Hurt, Plateau or Help?" zh="过剩参数有害、趋平还是有帮助？" />

<Para>
  <En>Figures~\ref{fig:100misoloss},~\ref{fig:400m1b5isoloss} suggest that excess parameters (or epochs) can harm performance. We hypothesize that this is due to suboptimal hyperparameters and could be prevented with better regularization. Thus, we expect with optimal regularization hyperparameters excess parameters would never hurt, but performance would merely plateau, as in extreme cases regularization could just take the form of removing the excess parameters. One approach to selecting optimal hyperparameters is $\mu$P~\cite{yang2021tuning}. We compare excessively large models trained with a data constraint of $D_C=100$ million tokens in \autoref{fig:mup} across $\mu$P, our default hyperparameters (\autoref{sec:arch}) and scaling law predictions. Surprisingly, $\mu$P leads to even higher test loss than our default hyperparameters. Nevertheless, we find that also with $\mu$P excessive parameters hurt: The models with more than 2 billion parameters have significantly higher validation loss after training than the models with 200 million to 1 billion parameters when trained on only 100 million tokens. However, $\mu$P only covers hyperparameters such as the learning rate, but not explicit regularization hyperparameters like dropout rates, which we hypothesize would prevent this behavior. Thus, our proposed scaling equations predict loss to plateau, as seen in the straight line. As the compute-optimal parameter count for 100 million tokens is around 7 million, all depicted models have a significant amount of excess parameters and data-constrained scaling laws predict their losses to be all the same ($R_N^* \ll R_N$). Meanwhile, the default Chinchilla scaling law~\cite{hoffmann2022training} predicts loss to continue decreasing as parameters are added, which is in stark contrast to the empirical data.</En>
  <Zh>图~\ref{fig:100misoloss}、~\ref{fig:400m1b5isoloss} 表明过剩参数（或 epoch）可能损害性能。我们假设这是超参数欠佳所致，并可通过更好的正则化加以避免。因此我们预计，在最优正则化超参数下，过剩参数永远不会有害，性能只会趋平——极端情况下正则化可以直接表现为移除过剩参数。选择最优超参数的一种方法是 $\mu$P~\cite{yang2021tuning}。在 \autoref{fig:mup} 中，我们比较了在 $D_C=1$ 亿词元数据约束下以三种方式训练的过大模型：$\mu$P、我们的默认超参数（\autoref{sec:arch}）以及缩放定律预测。出乎意料的是，$\mu$P 导致的测试损失比我们的默认超参数更高。尽管如此，我们发现即使在 $\mu$P 下，过剩参数仍然有害：仅用 1 亿词元训练时，参数量超过 20 亿的模型训练后的验证损失显著高于 2 亿至 10 亿参数的模型。不过，$\mu$P 只涵盖学习率等超参数，并不包括丢弃率（dropout）这类显式正则化超参数，我们假设后者能够避免上述行为。因此，我们提出的缩放方程预测损失趋平，如直线所示。由于 1 亿词元的计算最优参数量约为 700 万，图中所有模型都有大量过剩参数，数据受限缩放定律预测它们的损失完全相同（$R_N^* \ll R_N$）。与此同时，默认的 Chinchilla 缩放定律~\cite{hoffmann2022training} 预测损失会随参数增加继续下降，这与实测数据形成鲜明对比。</Zh>
</Para>

<Para>
  <En>If one wants to incorporate excess parameters hurting performance into the scaling law equations, one could consider \textbf{(a)} Modifying the exponential decay formulation introduced in \autoref{sec:scalinglaws} such that instead of the value of repeated data decaying to $0$ it decays to a large negative value \textbf{(b)} decaying the exponents $\alpha$ and $\beta$ in \autoref{eq:cc} instead of $D$ and $N$. Decaying the exponents to $0$ has the effect of more repetitions eventually hurting performance as $\lim_{\alpha\to0}D^{\alpha} = 1$ and the same for $\beta$. Thus, initially as $D$ and $N$ increase loss decreases, but ultimately the decay of $\alpha$ and $\beta$ pushes $D$ and $N$ back to $1$ resulting in loss to increase. Specifically, approach \textbf{(b)} could take the form of:</En>
  <Zh>如果要把“过剩参数损害性能”纳入缩放定律方程，可以考虑：\textbf{(a)} 修改 \autoref{sec:scalinglaws} 引入的指数衰减形式，使重复数据的价值不是衰减到 $0$，而是衰减到一个较大的负值；或 \textbf{(b)} 衰减 \autoref{eq:cc} 中的指数 $\alpha$ 与 $\beta$ 而非 $D$ 与 $N$。把指数衰减到 $0$ 的效果是重复次数越多最终越损害性能，因为 $\lim_{\alpha\to0}D^{\alpha} = 1$，$\beta$ 同理。于是，起初随着 $D$ 与 $N$ 增加损失下降，但最终 $\alpha$ 与 $\beta$ 的衰减会把 $D$ 与 $N$ 拉回 $1$，使损失回升。具体地，方案 \textbf{(b)} 可以采取如下形式：</Zh>
</Para>

<Equation  label="eq:alphabeta" latex="L(N,D,R_N,R_D)=E + \frac{A}{N^{\alpha * max(0, 1 - (R_N/R_N^*))}} + \frac{B}{D^{\beta * max(0, 1 - (R_D/R_D^*))}}"
  :tips="{ L: '预测损失（alpha-beta 衰减版公式）', N: '模型参数量', D: '训练词元数', 'R_N': '参数“重复”次数', 'R_D': '数据重复次数', 'R_N^*': '参数重复临界值（学得）', 'R_D^*': '数据重复临界值（学得）', E: '不可约损失下限', A: '参数项系数', B: '数据项系数', '\\alpha': '参数项指数：随重复衰减，过多重复反而推高损失', '\\beta': '数据项指数：随重复衰减' }" />

<Para>
  <En>Like the equations in \autoref{sec:scalinglaws} this formulation also reduces to the Chinchilla scaling laws in the base case of $R_D=0$ or $R_N=0$. As the exponents decrease with more repetitions adding parameters or epochs becomes less beneficial. Eventually, the decay in $\alpha$ or $\beta$ causes loss to increase again as it pushes $N$ or $D$ back down to $1$. We fit this formula using the same approach outlined in \autoref{sec:scalinglaws} but including samples where excess parameters or epochs hurt (296 total samples). We use a grid of initialization given by: $R_N^* \in \{0., 2000.,\dots, 100000. \}$ and $R_D^* \in \{0., 2000.,\dots, 100000. \}$. This results in $R_D^*=26530.611$ and $R_N^*=2040.8163$. $R_N^*$ is significantly lower resulting in excess parameters hurting faster than excess epochs, which is in line with empirical data from~\autoref{fig:100misoloss}. We visualize \autoref{fig:100misoloss} with the predictions from this alpha-beta decay formulation in \autoref{fig:alphabeta}. Expected parameters eventually hurt resulting in circle-shaped contours. Due to the very high $R_D^*$ the area where epochs start to hurt is outside of the boundaries of~\autoref{fig:alphabeta}. While the predicted optimal allocation (efficient frontier) is similar to~\autoref{fig:100misoloss}, the predicted return from repeated data differs significantly. The alpha-beta decay formulation incorrectly predicts returns to diminish significantly slower as seen by the longer efficient frontier and the smaller distance in contours early on as compared to~\autoref{fig:100misoloss}. Beyond its potentially useful properties, we do not have a rigorous mathematical justification for this alpha-beta decay formulation which could be the cause of the incorrect return predictions.</En>
  <Zh>与 \autoref{sec:scalinglaws} 中的方程一样，该形式在 $R_D=0$ 或 $R_N=0$ 的基准情形下也退化为 Chinchilla 缩放定律。随着重复次数增多、指数减小，增加参数或 epoch 的收益变小。最终，$\alpha$ 或 $\beta$ 的衰减会把 $N$ 或 $D$ 拉回 $1$，导致损失再次上升。我们采用 \autoref{sec:scalinglaws} 概述的同一方法拟合该公式，但纳入了过剩参数或 epoch 有害的样本（共 296 个样本）。初始值网格取为：$R_N^* \in \{0., 2000.,\dots, 100000. \}$ 与 $R_D^* \in \{0., 2000.,\dots, 100000. \}$。结果得到 $R_D^*=26530.611$、$R_N^*=2040.8163$。$R_N^*$ 显著更低，说明过剩参数比过剩 epoch 更快造成损害，这与~\autoref{fig:100misoloss} 的实测数据一致。我们在 \autoref{fig:alphabeta} 中用这一 alpha-beta 衰减形式的预测来可视化 \autoref{fig:100misoloss}。过剩参数最终有害，使等值线呈圆形。由于 $R_D^*$ 非常大，epoch 开始有害的区域超出了~\autoref{fig:alphabeta} 的边界。虽然预测的最优分配（有效前沿）与~\autoref{fig:100misoloss} 相似，但预测的重复数据回报差异显著：从更长的有效前沿以及早期更小的等值线间距可见，alpha-beta 衰减形式错误地预测回报衰减慢得多。除了其潜在的有用性质外，我们对这一 alpha-beta 衰减形式没有严格的数学论证，这可能是回报预测不正确的原因。</Zh>
</Para>

<Para>
  <En>Ultimately, we settle on our exponential decay formulation from~\autoref{sec:scalinglaws} that does not allow excess parameters or epochs to hurt, as preventing such behavior is trivial by stopping training (in the case of epochs hurting) or removing excess parameters (in the case of model parameters hurting). Further, accurately predicting how much loss increases in the limit is not very useful, as in practice one would want to stop training when it's expected to plateau anyways.</En>
  <Zh>最终，我们选择了~\autoref{sec:scalinglaws} 中不允许过剩参数或 epoch 造成损害的指数衰减形式，因为避免这种行为非常简单：在 epoch 有害时停止训练，在模型参数有害时移除过剩参数即可。此外，精确预测极限情形下损失上升多少并无太大用处，实践中人们本就会在预计趋平时停止训练。</Zh>
</Para>

<Figure src="figures/2305.16264/mup.svg" :width="100" label="fig:mup" caption-en="\textbf{Empirical and predicted losses of LLMs trained on 100 million tokens for a single epoch.} Excess parameters empirically hurt performance, but this may be due to a lack of regularization. Thus, our scaling formula predicts loss to plateau, while Chinchilla predicts loss to improve. By decaying the exponent $\alpha$ (and $\beta$) instead, one can allow excess parameters to hurt." caption-zh="\textbf{在 1 亿词元上单 epoch 训练的 LLM 的实测损失与预测损失。}实测中过剩参数损害性能，但这可能源于正则化不足。因此我们的缩放公式预测损失趋平，而 Chinchilla 预测损失改善。改为衰减指数 $\alpha$（与 $\beta$），则可以允许过剩参数有害。" />

<Figure src="figures/2305.16264/isoloss_alphabeta_100m.svg" :width="100" label="fig:alphabeta" caption-en="\textbf{IsoLoss contours for 100 million unique tokens with contours predicted by parametric decay of alpha and beta.} The same models from \autoref{fig:100misoloss} with the contour predictions being done by the alpha-beta decay formulation introduced in \autoref{sec:toomany}." caption-zh="\textbf{1 亿唯一词元的等损失等值线，等值线由 alpha 与 beta 的参数化衰减预测。}与 \autoref{fig:100misoloss} 相同的模型，等值线预测由 \autoref{sec:toomany} 引入的 alpha-beta 衰减形式给出。" />
</template>
