<!-- Case Study: Galactica -->
<script setup lang="ts">
import { Heading, Para, En, Zh, Figure } from '../../../components/paper'
</script>

<template>
<Heading :level="1" label="sec:limits" appendix en="Case Study: Galactica" zh="案例分析：Galactica" />

<Figure src="figures/2305.16264/galactica.svg" :width="100" label="fig:galactica" caption-en="\textbf{Optimal compute allocation for Galactica.} Efficient frontier assuming repeated data is worth the same as new data (Chinchilla scaling laws) and data-constrained efficient frontier assuming a unique token budget of 106 billion tokens like for the Galactica models~\cite{taylor2022galactica}. For optimal compute allocation according to our proposed data-constrained scaling laws, the 120 billion Galactica model should have been significantly smaller and trained for more epochs." caption-zh="\textbf{Galactica 的最优计算分配。}图中比较了假定重复数据与全新数据等价的有效前沿（Chinchilla 缩放定律），以及假定唯一词元预算为 1060 亿（与 Galactica 模型~\cite{taylor2022galactica} 相同）的数据受限有效前沿。按照我们所提数据受限缩放定律的最优计算分配，1200 亿参数的 Galactica 模型本应显著更小并训练更多 epoch。" />

<Para>
  <En>The Galactica models~\cite{taylor2022galactica} are the only publicly known LLMs that explicitly trained for a significant number of epochs prior to this work. They trained their models on 106 billion unique tokens for 4.25 epochs. Our findings on~\emph{Return} from repeated data agree with their conclusion that multiple epochs are beneficial, however, we find that even more epochs can be beneficial and a small spike in validation loss does not justify stopping training (\autoref{sec:addvalloss}). Meanwhile, our findings on \emph{Allocation} significantly deviate from Galactica. \autoref{fig:galactica} visualizes the Galactica models with our predicted efficient frontier in the same style as \autoref{fig:returnalloc}. The creators of Galactica decided to train a 120 billion parameter model on 450 billion tokens, a significant overallocation to parameters even in Chinchilla terms (black efficient frontier). This decision was likely driven by the intuition that repeated data is worth less, thus one should spend more compute on parameters. However, our empirical data contradicts this. Parameters learning from repeated data are worth \emph{even less} than repeated data, thus one should overallocate to epochs, not parameters. Our data-constrained scaling laws thus predict that a better model could have been trained by allocating significantly more FLOPs to epochs rather than parameters for the largest Galactica model with 120 billion parameters. Specifically, 40 billion parameters trained for 1.35 trillion tokens (12.75 epochs) would have been optimal according to data-constrained scaling laws. Note that these scaling laws have been fitted on C4, which is not the dataset used to pre-train Galactica. The Galactica models are pre-trained on a predominantly scientific dataset, which includes code data among other data sources. Results from~\cite{hoffmann2022training} show that there are differences in the scaling coefficients when training on C4 as compared to GitHub code, however, the overall allocation trend is the same. Thus, while we expect a smaller model trained for more epochs to be better than the 120 billion parameter model, the optimal allocation is unlikely to be exactly 40 billion parameters and 1.35 trillion tokens.</En>
  <Zh>Galactica 模型~\cite{taylor2022galactica} 是本工作之前唯一为公众所知、明确进行大量 epoch 训练的 LLM。他们在 1060 亿唯一词元上训练了 4.25 个 epoch。我们关于重复数据\emph{回报}的发现与其“多 epoch 有益”的结论一致；但我们发现更多 epoch 仍可能有益，且验证损失的小尖峰并不足以证明应停止训练（\autoref{sec:addvalloss}）。与此同时，我们关于\emph{分配}的发现与 Galactica 显著不同。\autoref{fig:galactica} 以与 \autoref{fig:returnalloc} 相同的风格、连同我们预测的有效前沿一起展示了 Galactica 模型。Galactica 的创建者决定在 4500 亿词元上训练 1200 亿参数的模型，即使按 Chinchilla 的标准（黑色有效前沿），这也是对参数的显著过度分配。这一决定可能源于“重复数据价值更低，因此应把更多计算花在参数上”的直觉。然而，我们的实证数据与此矛盾：从重复数据中学习的参数，其价值比重复数据\emph{更低}，因此应当把计算过度分配给 epoch 而非参数。因此，我们的数据受限缩放定律预测：对 1200 亿参数的最大 Galactica 模型而言，若把显著更多的 FLOPs 分配给 epoch 而非参数，本可以训练出更好的模型。具体而言，按数据受限缩放定律，400 亿参数训练 1.35 万亿词元（12.75 个 epoch）才是最优的。请注意，这些缩放定律是在 C4 上拟合的，而 C4 并非 Galactica 预训练所用的数据集。Galactica 模型在一个以科学文献为主的数据集上预训练，其中除其他数据源外还包含代码数据。\cite{hoffmann2022training} 的结果表明，在 C4 上训练与在 GitHub 代码上训练的缩放系数存在差异，但总体分配趋势相同。因此，虽然我们预计更小的模型训练更多 epoch 会优于 1200 亿参数模型，但最优分配不太可能恰好是 400 亿参数与 1.35 万亿词元。</Zh>
</Para>
</template>
